language: python
python:
  - "2.7"
services:
  - mysql
env:
  - DJANGO=1.8
install:
  - pip install --upgrade pip
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install mysql-python --use-mirrors
before_script:
  - mysql -e 'create database IF NOT EXISTS travis_ci_db;;' -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost';" -uroot
  - python manage.py migrate

#  - mysql -e 'create database travis_ci_db;'
#  - python manage.py syncdb --noinput
#  - "pep8 --exclude=migrations --ignore=E501,E225 src"
#  - pyflakes -x W src
script:
  - python manage.py test polls
